version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/web
    ports:
      - "8080:3000"
    environment:
      PORT: 3000
      SWAGGER_UI_PORT: 8080
    expose:
      - 3000
